// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/shared.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token_Type int32

const (
	Token_unknown     Token_Type = 0
	Token_sessionKey  Token_Type = 1
	Token_clientToken Token_Type = 2
)

var Token_Type_name = map[int32]string{
	0: "unknown",
	1: "sessionKey",
	2: "clientToken",
}

var Token_Type_value = map[string]int32{
	"unknown":     0,
	"sessionKey":  1,
	"clientToken": 2,
}

func (x Token_Type) String() string {
	return proto.EnumName(Token_Type_name, int32(x))
}

func (Token_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8d15baf0bbfbb79, []int{0, 0}
}

type Token struct {
	Token                string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type                 Token_Type `protobuf:"varint,2,opt,name=type,proto3,enum=roleypoly.auth.Token_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d15baf0bbfbb79, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetType() Token_Type {
	if m != nil {
		return m.Type
	}
	return Token_unknown
}

type AuthChallenge struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MagicUrl             string   `protobuf:"bytes,2,opt,name=magicUrl,proto3" json:"magicUrl,omitempty"`
	MagicWords           string   `protobuf:"bytes,3,opt,name=magicWords,proto3" json:"magicWords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthChallenge) Reset()         { *m = AuthChallenge{} }
func (m *AuthChallenge) String() string { return proto.CompactTextString(m) }
func (*AuthChallenge) ProtoMessage()    {}
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d15baf0bbfbb79, []int{1}
}

func (m *AuthChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthChallenge.Unmarshal(m, b)
}
func (m *AuthChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthChallenge.Marshal(b, m, deterministic)
}
func (m *AuthChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthChallenge.Merge(m, src)
}
func (m *AuthChallenge) XXX_Size() int {
	return xxx_messageInfo_AuthChallenge.Size(m)
}
func (m *AuthChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_AuthChallenge proto.InternalMessageInfo

func (m *AuthChallenge) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AuthChallenge) GetMagicUrl() string {
	if m != nil {
		return m.MagicUrl
	}
	return ""
}

func (m *AuthChallenge) GetMagicWords() string {
	if m != nil {
		return m.MagicWords
	}
	return ""
}

func init() {
	proto.RegisterEnum("roleypoly.auth.Token_Type", Token_Type_name, Token_Type_value)
	proto.RegisterType((*Token)(nil), "roleypoly.auth.Token")
	proto.RegisterType((*AuthChallenge)(nil), "roleypoly.auth.AuthChallenge")
}

func init() {
	proto.RegisterFile("auth/shared.proto", fileDescriptor_f8d15baf0bbfbb79)
}

var fileDescriptor_f8d15baf0bbfbb79 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x14, 0xc4, 0x4d, 0x6d, 0xab, 0x7d, 0xc5, 0x75, 0x0d, 0x22, 0x4b, 0x41, 0x2d, 0x7b, 0xea, 0x29,
	0x0b, 0xea, 0x17, 0xf0, 0xcf, 0x45, 0xbc, 0x2d, 0x15, 0xc1, 0xdb, 0x36, 0x7d, 0x6c, 0x96, 0xa6,
	0x49, 0xc8, 0x1f, 0x24, 0x67, 0xbf, 0xb8, 0x6c, 0x2c, 0x8b, 0xde, 0xe6, 0x97, 0xc9, 0xc0, 0xcc,
	0x83, 0x8b, 0x26, 0x78, 0x51, 0x39, 0xd1, 0x58, 0xdc, 0x32, 0x63, 0xb5, 0xd7, 0x34, 0xb3, 0x5a,
	0x62, 0x34, 0x5a, 0x46, 0xd6, 0x9b, 0xe5, 0x37, 0x81, 0xc9, 0x5a, 0xef, 0x50, 0xd1, 0x4b, 0x98,
	0xf8, 0x5e, 0x14, 0x64, 0x49, 0x56, 0xb3, 0xfa, 0x17, 0x28, 0x83, 0xb1, 0x8f, 0x06, 0x8b, 0xd1,
	0x92, 0xac, 0xb2, 0xbb, 0x05, 0xfb, 0x1f, 0x67, 0x29, 0xca, 0xd6, 0xd1, 0x60, 0x9d, 0xfe, 0x95,
	0x0f, 0x30, 0xee, 0x89, 0xce, 0xe1, 0x24, 0xa8, 0x9d, 0xd2, 0x5f, 0x2a, 0x3f, 0xa2, 0x19, 0x80,
	0x43, 0xe7, 0x3a, 0xad, 0xde, 0x30, 0xe6, 0x84, 0x9e, 0xc3, 0x9c, 0xcb, 0x0e, 0x95, 0x4f, 0xf1,
	0x7c, 0x54, 0x72, 0x38, 0x7b, 0x0c, 0x5e, 0x3c, 0x8b, 0x46, 0x4a, 0x54, 0x2d, 0xd2, 0x2b, 0x98,
	0x06, 0x87, 0xf6, 0xf5, 0xe5, 0xd0, 0xe6, 0x40, 0x74, 0x01, 0xa7, 0xfb, 0xa6, 0xed, 0xf8, 0xbb,
	0x95, 0xa9, 0xd2, 0xac, 0x1e, 0x98, 0xde, 0x00, 0x24, 0xfd, 0xa1, 0xed, 0xd6, 0x15, 0xc7, 0xc9,
	0xfd, 0xf3, 0xf2, 0x74, 0xfb, 0x79, 0xdd, 0x76, 0x5e, 0x84, 0x0d, 0xe3, 0x7a, 0x5f, 0x0d, 0x43,
	0x2a, 0x6b, 0x78, 0xd5, 0x8f, 0xd9, 0x4c, 0xd3, 0x89, 0xee, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0xc7, 0xc8, 0xe9, 0x37, 0x01, 0x00, 0x00,
}
