// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/backend/auth-backend.proto

package com_roleypoly_auth_backend

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserSlug struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSlug) Reset()         { *m = UserSlug{} }
func (m *UserSlug) String() string { return proto.CompactTextString(m) }
func (*UserSlug) ProtoMessage()    {}
func (*UserSlug) Descriptor() ([]byte, []int) {
	return fileDescriptor_5436ad1a948af874, []int{0}
}

func (m *UserSlug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSlug.Unmarshal(m, b)
}
func (m *UserSlug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSlug.Marshal(b, m, deterministic)
}
func (m *UserSlug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSlug.Merge(m, src)
}
func (m *UserSlug) XXX_Size() int {
	return xxx_messageInfo_UserSlug.Size(m)
}
func (m *UserSlug) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSlug.DiscardUnknown(m)
}

var xxx_messageInfo_UserSlug proto.InternalMessageInfo

func (m *UserSlug) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type AuthChallenge struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MagicUrl             string   `protobuf:"bytes,2,opt,name=magicUrl,proto3" json:"magicUrl,omitempty"`
	MagicWords           string   `protobuf:"bytes,3,opt,name=magicWords,proto3" json:"magicWords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthChallenge) Reset()         { *m = AuthChallenge{} }
func (m *AuthChallenge) String() string { return proto.CompactTextString(m) }
func (*AuthChallenge) ProtoMessage()    {}
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_5436ad1a948af874, []int{1}
}

func (m *AuthChallenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthChallenge.Unmarshal(m, b)
}
func (m *AuthChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthChallenge.Marshal(b, m, deterministic)
}
func (m *AuthChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthChallenge.Merge(m, src)
}
func (m *AuthChallenge) XXX_Size() int {
	return xxx_messageInfo_AuthChallenge.Size(m)
}
func (m *AuthChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_AuthChallenge proto.InternalMessageInfo

func (m *AuthChallenge) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AuthChallenge) GetMagicUrl() string {
	if m != nil {
		return m.MagicUrl
	}
	return ""
}

func (m *AuthChallenge) GetMagicWords() string {
	if m != nil {
		return m.MagicWords
	}
	return ""
}

func init() {
	proto.RegisterType((*UserSlug)(nil), "com.roleypoly.auth.backend.UserSlug")
	proto.RegisterType((*AuthChallenge)(nil), "com.roleypoly.auth.backend.AuthChallenge")
}

func init() { proto.RegisterFile("auth/backend/auth-backend.proto", fileDescriptor_5436ad1a948af874) }

var fileDescriptor_5436ad1a948af874 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x2c, 0x2d, 0xc9,
	0xd0, 0x4f, 0x4a, 0x4c, 0xce, 0x4e, 0xcd, 0x4b, 0xd1, 0x07, 0x71, 0x74, 0xa1, 0x1c, 0xbd, 0x82,
	0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xa9, 0xe4, 0xfc, 0x5c, 0xbd, 0xa2, 0xfc, 0x9c, 0xd4, 0xca, 0x82,
	0xfc, 0x9c, 0x4a, 0x3d, 0x90, 0x0a, 0x3d, 0xa8, 0x0a, 0x25, 0x25, 0x2e, 0x8e, 0xd0, 0xe2, 0xd4,
	0xa2, 0xe0, 0x9c, 0xd2, 0x74, 0x21, 0x31, 0x2e, 0xb6, 0xd2, 0xe2, 0xd4, 0x22, 0x4f, 0x17, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x29, 0x99, 0x8b, 0xd7, 0xb1, 0xb4, 0x24, 0xc3,
	0x39, 0x23, 0x31, 0x27, 0x27, 0x35, 0x2f, 0x3d, 0x15, 0x97, 0x42, 0x21, 0x29, 0x2e, 0x8e, 0xdc,
	0xc4, 0xf4, 0xcc, 0xe4, 0xd0, 0xa2, 0x1c, 0x09, 0x26, 0xb0, 0x0c, 0x9c, 0x2f, 0x24, 0xc7, 0xc5,
	0x05, 0x66, 0x87, 0xe7, 0x17, 0xa5, 0x14, 0x4b, 0x30, 0x83, 0x65, 0x91, 0x44, 0x8c, 0xca, 0xb9,
	0xb8, 0x41, 0x96, 0x38, 0x41, 0xdc, 0x25, 0x94, 0xc1, 0x25, 0xec, 0x9e, 0x5a, 0x12, 0x9c, 0x5a,
	0x5c, 0x9c, 0x99, 0x9f, 0x87, 0xb0, 0x59, 0x45, 0x0f, 0xb7, 0x5f, 0xf4, 0x60, 0x1e, 0x91, 0xd2,
	0xc4, 0xa7, 0x0a, 0xc5, 0x2b, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0x40, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0xf5, 0xa2, 0xd3, 0x47, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthBackendClient is the client API for AuthBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthBackendClient interface {
	GetSessionChallenge(ctx context.Context, in *UserSlug, opts ...grpc.CallOption) (*AuthChallenge, error)
}

type authBackendClient struct {
	cc *grpc.ClientConn
}

func NewAuthBackendClient(cc *grpc.ClientConn) AuthBackendClient {
	return &authBackendClient{cc}
}

func (c *authBackendClient) GetSessionChallenge(ctx context.Context, in *UserSlug, opts ...grpc.CallOption) (*AuthChallenge, error) {
	out := new(AuthChallenge)
	err := c.cc.Invoke(ctx, "/com.roleypoly.auth.backend.AuthBackend/GetSessionChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthBackendServer is the server API for AuthBackend service.
type AuthBackendServer interface {
	GetSessionChallenge(context.Context, *UserSlug) (*AuthChallenge, error)
}

// UnimplementedAuthBackendServer can be embedded to have forward compatible implementations.
type UnimplementedAuthBackendServer struct {
}

func (*UnimplementedAuthBackendServer) GetSessionChallenge(ctx context.Context, req *UserSlug) (*AuthChallenge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionChallenge not implemented")
}

func RegisterAuthBackendServer(s *grpc.Server, srv AuthBackendServer) {
	s.RegisterService(&_AuthBackend_serviceDesc, srv)
}

func _AuthBackend_GetSessionChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSlug)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthBackendServer).GetSessionChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.roleypoly.auth.backend.AuthBackend/GetSessionChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthBackendServer).GetSessionChallenge(ctx, req.(*UserSlug))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.roleypoly.auth.backend.AuthBackend",
	HandlerType: (*AuthBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSessionChallenge",
			Handler:    _AuthBackend_GetSessionChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/backend/auth-backend.proto",
}
