// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform/platform.proto

package platform

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	discord "github.com/roleypoly/rpc/discord"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("platform/platform.proto", fileDescriptor_fa9581d889443fc5) }

var fileDescriptor_fa9581d889443fc5 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xc8, 0x49, 0x2c,
	0x49, 0xcb, 0x2f, 0xca, 0xd5, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xc4, 0x92,
	0xf3, 0x73, 0xf5, 0x8a, 0xf2, 0x73, 0x52, 0x2b, 0x0b, 0xf2, 0x73, 0x2a, 0xf5, 0x60, 0xb2, 0x52,
	0xa2, 0x29, 0x99, 0xc5, 0xc9, 0xf9, 0x45, 0x29, 0xfa, 0x50, 0x1a, 0xa2, 0xdc, 0x28, 0x8c, 0x8b,
	0x23, 0x00, 0xaa, 0x44, 0xc8, 0x8b, 0x8b, 0xc3, 0x3d, 0xb5, 0xc4, 0xbd, 0x34, 0x33, 0x27, 0x45,
	0x48, 0x4e, 0x0f, 0xd5, 0x1c, 0x98, 0x2e, 0x4f, 0x97, 0xc0, 0xd2, 0xd4, 0xa2, 0x4a, 0x29, 0x19,
	0x1c, 0xf2, 0x60, 0xdd, 0x4a, 0x0c, 0x4e, 0xca, 0x51, 0x8a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49,
	0x20, 0x75, 0xfa, 0x70, 0x75, 0xfa, 0x45, 0x05, 0xc9, 0x70, 0x17, 0x27, 0xb1, 0x81, 0xdd, 0x60,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x50, 0x42, 0x8d, 0xc5, 0xcd, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformClient interface {
	GetGuild(ctx context.Context, in *discord.IDQuery, opts ...grpc.CallOption) (*discord.Guild, error)
}

type platformClient struct {
	cc *grpc.ClientConn
}

func NewPlatformClient(cc *grpc.ClientConn) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) GetGuild(ctx context.Context, in *discord.IDQuery, opts ...grpc.CallOption) (*discord.Guild, error) {
	out := new(discord.Guild)
	err := c.cc.Invoke(ctx, "/com.roleypoly.platform.Platform/GetGuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
type PlatformServer interface {
	GetGuild(context.Context, *discord.IDQuery) (*discord.Guild, error)
}

// UnimplementedPlatformServer can be embedded to have forward compatible implementations.
type UnimplementedPlatformServer struct {
}

func (*UnimplementedPlatformServer) GetGuild(ctx context.Context, req *discord.IDQuery) (*discord.Guild, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuild not implemented")
}

func RegisterPlatformServer(s *grpc.Server, srv PlatformServer) {
	s.RegisterService(&_Platform_serviceDesc, srv)
}

func _Platform_GetGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(discord.IDQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.roleypoly.platform.Platform/GetGuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetGuild(ctx, req.(*discord.IDQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Platform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.roleypoly.platform.Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGuild",
			Handler:    _Platform_GetGuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/platform.proto",
}
