// source: platform/platform.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var shared_shared_pb = require('../shared/shared_pb.js');
goog.object.extend(proto, shared_shared_pb);
var discord_discord_pb = require('../discord/discord_pb.js');
goog.object.extend(proto, discord_discord_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.roleypoly.platform.Category', null, global);
goog.exportSymbol('proto.roleypoly.platform.Category.CategoryType', null, global);
goog.exportSymbol('proto.roleypoly.platform.GuildData', null, global);
goog.exportSymbol('proto.roleypoly.platform.GuildEnumeration', null, global);
goog.exportSymbol('proto.roleypoly.platform.PresentableGuild', null, global);
goog.exportSymbol('proto.roleypoly.platform.Roles', null, global);
goog.exportSymbol('proto.roleypoly.platform.UpdateEntitlement', null, global);
goog.exportSymbol('proto.roleypoly.platform.UpdateRoles', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.GuildEnumeration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.roleypoly.platform.GuildEnumeration.repeatedFields_, null);
};
goog.inherits(proto.roleypoly.platform.GuildEnumeration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.GuildEnumeration.displayName = 'proto.roleypoly.platform.GuildEnumeration';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.PresentableGuild = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.roleypoly.platform.PresentableGuild, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.PresentableGuild.displayName = 'proto.roleypoly.platform.PresentableGuild';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.GuildData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.roleypoly.platform.GuildData.repeatedFields_, null);
};
goog.inherits(proto.roleypoly.platform.GuildData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.GuildData.displayName = 'proto.roleypoly.platform.GuildData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.UpdateRoles = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.roleypoly.platform.UpdateRoles, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.UpdateRoles.displayName = 'proto.roleypoly.platform.UpdateRoles';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.Roles = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.roleypoly.platform.Roles.repeatedFields_, null);
};
goog.inherits(proto.roleypoly.platform.Roles, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.Roles.displayName = 'proto.roleypoly.platform.Roles';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.Category = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.roleypoly.platform.Category.repeatedFields_, null);
};
goog.inherits(proto.roleypoly.platform.Category, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.Category.displayName = 'proto.roleypoly.platform.Category';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.platform.UpdateEntitlement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.roleypoly.platform.UpdateEntitlement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.platform.UpdateEntitlement.displayName = 'proto.roleypoly.platform.UpdateEntitlement';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.roleypoly.platform.GuildEnumeration.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.GuildEnumeration.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.GuildEnumeration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.GuildEnumeration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.GuildEnumeration.toObject = function(includeInstance, msg) {
  var f, obj = {
    guildsList: jspb.Message.toObjectList(msg.getGuildsList(),
    proto.roleypoly.platform.PresentableGuild.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.GuildEnumeration}
 */
proto.roleypoly.platform.GuildEnumeration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.GuildEnumeration;
  return proto.roleypoly.platform.GuildEnumeration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.GuildEnumeration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.GuildEnumeration}
 */
proto.roleypoly.platform.GuildEnumeration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.roleypoly.platform.PresentableGuild;
      reader.readMessage(value,proto.roleypoly.platform.PresentableGuild.deserializeBinaryFromReader);
      msg.addGuilds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.GuildEnumeration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.GuildEnumeration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.GuildEnumeration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.GuildEnumeration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGuildsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.roleypoly.platform.PresentableGuild.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PresentableGuild guilds = 1;
 * @return {!Array<!proto.roleypoly.platform.PresentableGuild>}
 */
proto.roleypoly.platform.GuildEnumeration.prototype.getGuildsList = function() {
  return /** @type{!Array<!proto.roleypoly.platform.PresentableGuild>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.roleypoly.platform.PresentableGuild, 1));
};


/** @param {!Array<!proto.roleypoly.platform.PresentableGuild>} value */
proto.roleypoly.platform.GuildEnumeration.prototype.setGuildsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.roleypoly.platform.PresentableGuild=} opt_value
 * @param {number=} opt_index
 * @return {!proto.roleypoly.platform.PresentableGuild}
 */
proto.roleypoly.platform.GuildEnumeration.prototype.addGuilds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.roleypoly.platform.PresentableGuild, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.roleypoly.platform.GuildEnumeration.prototype.clearGuildsList = function() {
  this.setGuildsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.PresentableGuild.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.PresentableGuild.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.PresentableGuild} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.PresentableGuild.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    guild: (f = msg.getGuild()) && shared_shared_pb.Guild.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.roleypoly.platform.GuildData.toObject(includeInstance, f),
    member: (f = msg.getMember()) && discord_discord_pb.Member.toObject(includeInstance, f),
    roles: (f = msg.getRoles()) && shared_shared_pb.GuildRoles.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.PresentableGuild}
 */
proto.roleypoly.platform.PresentableGuild.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.PresentableGuild;
  return proto.roleypoly.platform.PresentableGuild.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.PresentableGuild} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.PresentableGuild}
 */
proto.roleypoly.platform.PresentableGuild.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new shared_shared_pb.Guild;
      reader.readMessage(value,shared_shared_pb.Guild.deserializeBinaryFromReader);
      msg.setGuild(value);
      break;
    case 3:
      var value = new proto.roleypoly.platform.GuildData;
      reader.readMessage(value,proto.roleypoly.platform.GuildData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 4:
      var value = new discord_discord_pb.Member;
      reader.readMessage(value,discord_discord_pb.Member.deserializeBinaryFromReader);
      msg.setMember(value);
      break;
    case 5:
      var value = new shared_shared_pb.GuildRoles;
      reader.readMessage(value,shared_shared_pb.GuildRoles.deserializeBinaryFromReader);
      msg.setRoles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.PresentableGuild.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.PresentableGuild.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.PresentableGuild} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.PresentableGuild.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGuild();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      shared_shared_pb.Guild.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.roleypoly.platform.GuildData.serializeBinaryToWriter
    );
  }
  f = message.getMember();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      discord_discord_pb.Member.serializeBinaryToWriter
    );
  }
  f = message.getRoles();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      shared_shared_pb.GuildRoles.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.roleypoly.platform.PresentableGuild.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.roleypoly.platform.PresentableGuild.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional roleypoly.Guild guild = 2;
 * @return {?proto.roleypoly.Guild}
 */
proto.roleypoly.platform.PresentableGuild.prototype.getGuild = function() {
  return /** @type{?proto.roleypoly.Guild} */ (
    jspb.Message.getWrapperField(this, shared_shared_pb.Guild, 2));
};


/** @param {?proto.roleypoly.Guild|undefined} value */
proto.roleypoly.platform.PresentableGuild.prototype.setGuild = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.platform.PresentableGuild.prototype.clearGuild = function() {
  this.setGuild(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.platform.PresentableGuild.prototype.hasGuild = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GuildData data = 3;
 * @return {?proto.roleypoly.platform.GuildData}
 */
proto.roleypoly.platform.PresentableGuild.prototype.getData = function() {
  return /** @type{?proto.roleypoly.platform.GuildData} */ (
    jspb.Message.getWrapperField(this, proto.roleypoly.platform.GuildData, 3));
};


/** @param {?proto.roleypoly.platform.GuildData|undefined} value */
proto.roleypoly.platform.PresentableGuild.prototype.setData = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.platform.PresentableGuild.prototype.clearData = function() {
  this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.platform.PresentableGuild.prototype.hasData = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional roleypoly.discord.Member member = 4;
 * @return {?proto.roleypoly.discord.Member}
 */
proto.roleypoly.platform.PresentableGuild.prototype.getMember = function() {
  return /** @type{?proto.roleypoly.discord.Member} */ (
    jspb.Message.getWrapperField(this, discord_discord_pb.Member, 4));
};


/** @param {?proto.roleypoly.discord.Member|undefined} value */
proto.roleypoly.platform.PresentableGuild.prototype.setMember = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.platform.PresentableGuild.prototype.clearMember = function() {
  this.setMember(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.platform.PresentableGuild.prototype.hasMember = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional roleypoly.GuildRoles roles = 5;
 * @return {?proto.roleypoly.GuildRoles}
 */
proto.roleypoly.platform.PresentableGuild.prototype.getRoles = function() {
  return /** @type{?proto.roleypoly.GuildRoles} */ (
    jspb.Message.getWrapperField(this, shared_shared_pb.GuildRoles, 5));
};


/** @param {?proto.roleypoly.GuildRoles|undefined} value */
proto.roleypoly.platform.PresentableGuild.prototype.setRoles = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.platform.PresentableGuild.prototype.clearRoles = function() {
  this.setRoles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.platform.PresentableGuild.prototype.hasRoles = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.roleypoly.platform.GuildData.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.GuildData.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.GuildData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.GuildData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.GuildData.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    categoriesList: jspb.Message.toObjectList(msg.getCategoriesList(),
    proto.roleypoly.platform.Category.toObject, includeInstance),
    entitlementsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.GuildData}
 */
proto.roleypoly.platform.GuildData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.GuildData;
  return proto.roleypoly.platform.GuildData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.GuildData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.GuildData}
 */
proto.roleypoly.platform.GuildData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = new proto.roleypoly.platform.Category;
      reader.readMessage(value,proto.roleypoly.platform.Category.deserializeBinaryFromReader);
      msg.addCategories(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addEntitlements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.GuildData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.GuildData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.GuildData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.GuildData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.roleypoly.platform.Category.serializeBinaryToWriter
    );
  }
  f = message.getEntitlementsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.roleypoly.platform.GuildData.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.roleypoly.platform.GuildData.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.roleypoly.platform.GuildData.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.roleypoly.platform.GuildData.prototype.setMessage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Category categories = 3;
 * @return {!Array<!proto.roleypoly.platform.Category>}
 */
proto.roleypoly.platform.GuildData.prototype.getCategoriesList = function() {
  return /** @type{!Array<!proto.roleypoly.platform.Category>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.roleypoly.platform.Category, 3));
};


/** @param {!Array<!proto.roleypoly.platform.Category>} value */
proto.roleypoly.platform.GuildData.prototype.setCategoriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.roleypoly.platform.Category=} opt_value
 * @param {number=} opt_index
 * @return {!proto.roleypoly.platform.Category}
 */
proto.roleypoly.platform.GuildData.prototype.addCategories = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.roleypoly.platform.Category, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.roleypoly.platform.GuildData.prototype.clearCategoriesList = function() {
  this.setCategoriesList([]);
};


/**
 * repeated string entitlements = 4;
 * @return {!Array<string>}
 */
proto.roleypoly.platform.GuildData.prototype.getEntitlementsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<string>} value */
proto.roleypoly.platform.GuildData.prototype.setEntitlementsList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.roleypoly.platform.GuildData.prototype.addEntitlements = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.roleypoly.platform.GuildData.prototype.clearEntitlementsList = function() {
  this.setEntitlementsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.UpdateRoles.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.UpdateRoles.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.UpdateRoles} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.UpdateRoles.toObject = function(includeInstance, msg) {
  var f, obj = {
    guildid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    roles: (f = msg.getRoles()) && proto.roleypoly.platform.Roles.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.UpdateRoles}
 */
proto.roleypoly.platform.UpdateRoles.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.UpdateRoles;
  return proto.roleypoly.platform.UpdateRoles.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.UpdateRoles} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.UpdateRoles}
 */
proto.roleypoly.platform.UpdateRoles.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuildid(value);
      break;
    case 2:
      var value = new proto.roleypoly.platform.Roles;
      reader.readMessage(value,proto.roleypoly.platform.Roles.deserializeBinaryFromReader);
      msg.setRoles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.UpdateRoles.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.UpdateRoles.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.UpdateRoles} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.UpdateRoles.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGuildid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRoles();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.roleypoly.platform.Roles.serializeBinaryToWriter
    );
  }
};


/**
 * optional string guildID = 1;
 * @return {string}
 */
proto.roleypoly.platform.UpdateRoles.prototype.getGuildid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.roleypoly.platform.UpdateRoles.prototype.setGuildid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Roles roles = 2;
 * @return {?proto.roleypoly.platform.Roles}
 */
proto.roleypoly.platform.UpdateRoles.prototype.getRoles = function() {
  return /** @type{?proto.roleypoly.platform.Roles} */ (
    jspb.Message.getWrapperField(this, proto.roleypoly.platform.Roles, 2));
};


/** @param {?proto.roleypoly.platform.Roles|undefined} value */
proto.roleypoly.platform.UpdateRoles.prototype.setRoles = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.platform.UpdateRoles.prototype.clearRoles = function() {
  this.setRoles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.platform.UpdateRoles.prototype.hasRoles = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.roleypoly.platform.Roles.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.Roles.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.Roles.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.Roles} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.Roles.toObject = function(includeInstance, msg) {
  var f, obj = {
    rolesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.Roles}
 */
proto.roleypoly.platform.Roles.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.Roles;
  return proto.roleypoly.platform.Roles.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.Roles} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.Roles}
 */
proto.roleypoly.platform.Roles.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addRoles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.Roles.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.Roles.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.Roles} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.Roles.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string roles = 1;
 * @return {!Array<string>}
 */
proto.roleypoly.platform.Roles.prototype.getRolesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.roleypoly.platform.Roles.prototype.setRolesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.roleypoly.platform.Roles.prototype.addRoles = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.roleypoly.platform.Roles.prototype.clearRolesList = function() {
  this.setRolesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.roleypoly.platform.Category.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.Category.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.Category.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.Category} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.Category.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    rolesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    hidden: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    type: jspb.Message.getFieldWithDefault(msg, 5, 0),
    position: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.Category}
 */
proto.roleypoly.platform.Category.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.Category;
  return proto.roleypoly.platform.Category.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.Category} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.Category}
 */
proto.roleypoly.platform.Category.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addRoles(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHidden(value);
      break;
    case 5:
      var value = /** @type {!proto.roleypoly.platform.Category.CategoryType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPosition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.Category.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.Category.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.Category} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.Category.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getHidden();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getPosition();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.roleypoly.platform.Category.CategoryType = {
  MULTI: 0,
  SINGLE: 1
};

/**
 * optional string ID = 1;
 * @return {string}
 */
proto.roleypoly.platform.Category.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.roleypoly.platform.Category.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.roleypoly.platform.Category.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.roleypoly.platform.Category.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string roles = 3;
 * @return {!Array<string>}
 */
proto.roleypoly.platform.Category.prototype.getRolesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.roleypoly.platform.Category.prototype.setRolesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.roleypoly.platform.Category.prototype.addRoles = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.roleypoly.platform.Category.prototype.clearRolesList = function() {
  this.setRolesList([]);
};


/**
 * optional bool hidden = 4;
 * @return {boolean}
 */
proto.roleypoly.platform.Category.prototype.getHidden = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.roleypoly.platform.Category.prototype.setHidden = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional CategoryType type = 5;
 * @return {!proto.roleypoly.platform.Category.CategoryType}
 */
proto.roleypoly.platform.Category.prototype.getType = function() {
  return /** @type {!proto.roleypoly.platform.Category.CategoryType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.roleypoly.platform.Category.CategoryType} value */
proto.roleypoly.platform.Category.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional int32 position = 6;
 * @return {number}
 */
proto.roleypoly.platform.Category.prototype.getPosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.roleypoly.platform.Category.prototype.setPosition = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.platform.UpdateEntitlement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.platform.UpdateEntitlement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.UpdateEntitlement.toObject = function(includeInstance, msg) {
  var f, obj = {
    query: (f = msg.getQuery()) && shared_shared_pb.IDQuery.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    state: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.platform.UpdateEntitlement}
 */
proto.roleypoly.platform.UpdateEntitlement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.platform.UpdateEntitlement;
  return proto.roleypoly.platform.UpdateEntitlement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.platform.UpdateEntitlement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.platform.UpdateEntitlement}
 */
proto.roleypoly.platform.UpdateEntitlement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_shared_pb.IDQuery;
      reader.readMessage(value,shared_shared_pb.IDQuery.deserializeBinaryFromReader);
      msg.setQuery(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.platform.UpdateEntitlement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.platform.UpdateEntitlement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.platform.UpdateEntitlement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_shared_pb.IDQuery.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getState();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional roleypoly.IDQuery query = 1;
 * @return {?proto.roleypoly.IDQuery}
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.getQuery = function() {
  return /** @type{?proto.roleypoly.IDQuery} */ (
    jspb.Message.getWrapperField(this, shared_shared_pb.IDQuery, 1));
};


/** @param {?proto.roleypoly.IDQuery|undefined} value */
proto.roleypoly.platform.UpdateEntitlement.prototype.setQuery = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.clearQuery = function() {
  this.setQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.hasQuery = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.roleypoly.platform.UpdateEntitlement.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool state = 3;
 * @return {boolean}
 */
proto.roleypoly.platform.UpdateEntitlement.prototype.getState = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.roleypoly.platform.UpdateEntitlement.prototype.setState = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


goog.object.extend(exports, proto.roleypoly.platform);
