// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform/platform.proto

package platform

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	shared "shared"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category_CategoryType int32

const (
	Category_multi  Category_CategoryType = 0
	Category_single Category_CategoryType = 1
)

var Category_CategoryType_name = map[int32]string{
	0: "multi",
	1: "single",
}

var Category_CategoryType_value = map[string]int32{
	"multi":  0,
	"single": 1,
}

func (x Category_CategoryType) String() string {
	return proto.EnumName(Category_CategoryType_name, int32(x))
}

func (Category_CategoryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa9581d889443fc5, []int{2, 0}
}

type GuildData struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Categories           []*Category `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Entitlements         []string    `protobuf:"bytes,4,rep,name=entitlements,proto3" json:"entitlements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GuildData) Reset()         { *m = GuildData{} }
func (m *GuildData) String() string { return proto.CompactTextString(m) }
func (*GuildData) ProtoMessage()    {}
func (*GuildData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9581d889443fc5, []int{0}
}

func (m *GuildData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuildData.Unmarshal(m, b)
}
func (m *GuildData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuildData.Marshal(b, m, deterministic)
}
func (m *GuildData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuildData.Merge(m, src)
}
func (m *GuildData) XXX_Size() int {
	return xxx_messageInfo_GuildData.Size(m)
}
func (m *GuildData) XXX_DiscardUnknown() {
	xxx_messageInfo_GuildData.DiscardUnknown(m)
}

var xxx_messageInfo_GuildData proto.InternalMessageInfo

func (m *GuildData) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GuildData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GuildData) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *GuildData) GetEntitlements() []string {
	if m != nil {
		return m.Entitlements
	}
	return nil
}

type Roles struct {
	Roles                []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Roles) Reset()         { *m = Roles{} }
func (m *Roles) String() string { return proto.CompactTextString(m) }
func (*Roles) ProtoMessage()    {}
func (*Roles) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9581d889443fc5, []int{1}
}

func (m *Roles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Roles.Unmarshal(m, b)
}
func (m *Roles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Roles.Marshal(b, m, deterministic)
}
func (m *Roles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Roles.Merge(m, src)
}
func (m *Roles) XXX_Size() int {
	return xxx_messageInfo_Roles.Size(m)
}
func (m *Roles) XXX_DiscardUnknown() {
	xxx_messageInfo_Roles.DiscardUnknown(m)
}

var xxx_messageInfo_Roles proto.InternalMessageInfo

func (m *Roles) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Category struct {
	ID                   string                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Roles                []string              `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Hidden               bool                  `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Type                 Category_CategoryType `protobuf:"varint,5,opt,name=type,proto3,enum=roleypoly.platform.Category_CategoryType" json:"type,omitempty"`
	Position             int32                 `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9581d889443fc5, []int{2}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Category) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Category) GetType() Category_CategoryType {
	if m != nil {
		return m.Type
	}
	return Category_multi
}

func (m *Category) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func init() {
	proto.RegisterEnum("roleypoly.platform.Category_CategoryType", Category_CategoryType_name, Category_CategoryType_value)
	proto.RegisterType((*GuildData)(nil), "roleypoly.platform.GuildData")
	proto.RegisterType((*Roles)(nil), "roleypoly.platform.Roles")
	proto.RegisterType((*Category)(nil), "roleypoly.platform.Category")
}

func init() { proto.RegisterFile("platform/platform.proto", fileDescriptor_fa9581d889443fc5) }

var fileDescriptor_fa9581d889443fc5 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0x38, 0x38, 0x93, 0xaa, 0x44, 0x43, 0x55, 0x8c, 0xa1, 0x92, 0x31, 0x42, 0x32,
	0x17, 0x5b, 0x0a, 0x57, 0x7a, 0x69, 0x83, 0xa2, 0x20, 0x90, 0xc0, 0x82, 0x0b, 0x37, 0x27, 0x9e,
	0x3a, 0x2b, 0x79, 0xbd, 0x2b, 0xef, 0xfa, 0xe0, 0x1f, 0xc1, 0x99, 0x7f, 0xc7, 0x6f, 0x41, 0x5d,
	0xd7, 0xae, 0xa1, 0x1f, 0x27, 0xcf, 0x9b, 0x79, 0xf3, 0xfc, 0xec, 0xb7, 0x0b, 0xcf, 0x65, 0x91,
	0xea, 0x2b, 0x51, 0xf1, 0xb8, 0x2b, 0x22, 0x59, 0x09, 0x2d, 0x10, 0x2b, 0x51, 0x50, 0x23, 0x45,
	0xd1, 0x44, 0xdd, 0xc4, 0x7b, 0xa6, 0x0e, 0x69, 0x45, 0x59, 0xdc, 0x3e, 0x5a, 0xa2, 0xf7, 0x32,
	0x17, 0x22, 0x2f, 0x28, 0x36, 0x68, 0x57, 0x5f, 0xc5, 0xc4, 0xa5, 0x6e, 0xda, 0x61, 0xf0, 0xdb,
	0x82, 0xf9, 0xa6, 0x66, 0x45, 0xb6, 0x4e, 0x75, 0x8a, 0xc7, 0x30, 0xde, 0xae, 0x5d, 0xcb, 0xb7,
	0xc2, 0x79, 0x32, 0xde, 0xae, 0xd1, 0x85, 0x27, 0x9c, 0x94, 0x4a, 0x73, 0x72, 0xc7, 0xa6, 0xd9,
	0x41, 0xfc, 0x00, 0xb0, 0x4f, 0x35, 0xe5, 0xa2, 0x62, 0xa4, 0xdc, 0x89, 0x3f, 0x09, 0x17, 0xab,
	0x57, 0xd1, 0x5d, 0x4b, 0xd1, 0x65, 0xcb, 0x6a, 0x92, 0x01, 0x1f, 0x03, 0x38, 0xa2, 0x52, 0x33,
	0x5d, 0x10, 0xa7, 0x52, 0x2b, 0x77, 0xea, 0x4f, 0xc2, 0x79, 0xf2, 0x4f, 0x2f, 0x38, 0x03, 0x3b,
	0x11, 0x05, 0x29, 0x3c, 0x01, 0xfb, 0x5a, 0x57, 0xb9, 0x96, 0x61, 0xb5, 0x20, 0xf8, 0x63, 0x81,
	0xd3, 0x69, 0xdf, 0xf1, 0x8d, 0x30, 0x2d, 0x53, 0xde, 0x99, 0x36, 0xf5, 0xad, 0xcc, 0x64, 0x20,
	0x83, 0xa7, 0x30, 0x3b, 0xb0, 0x2c, 0xa3, 0xd2, 0x9d, 0xfa, 0x56, 0xe8, 0x24, 0x37, 0x08, 0xcf,
	0x61, 0xaa, 0x1b, 0x49, 0xae, 0xed, 0x5b, 0xe1, 0xf1, 0xea, 0xdd, 0x63, 0x5f, 0xd6, 0x17, 0xdf,
	0x1b, 0x49, 0x89, 0x59, 0x43, 0x0f, 0x1c, 0x29, 0x14, 0xd3, 0x4c, 0x94, 0xee, 0xcc, 0xb7, 0x42,
	0x3b, 0xe9, 0x71, 0xf0, 0x16, 0x8e, 0x86, 0x1b, 0x38, 0x07, 0x9b, 0xd7, 0x85, 0x66, 0xcb, 0x11,
	0x02, 0xcc, 0x14, 0x2b, 0xf3, 0x82, 0x96, 0xd6, 0xea, 0xd7, 0x18, 0x9c, 0xaf, 0x37, 0xef, 0xc2,
	0x73, 0x58, 0x6c, 0x48, 0x7f, 0x69, 0x4c, 0x54, 0x0a, 0x4f, 0xa3, 0x36, 0xd3, 0xa8, 0xcb, 0x34,
	0xfa, 0x78, 0x9d, 0xa9, 0x77, 0x32, 0xf0, 0x69, 0xa8, 0x9f, 0x99, 0xd2, 0xc1, 0x08, 0x57, 0xe0,
	0x6c, 0x48, 0x9b, 0x0e, 0xe2, 0x80, 0xb3, 0x5d, 0x7f, 0xab, 0xa9, 0x6a, 0xbc, 0xe5, 0xff, 0x7b,
	0xc1, 0x08, 0x3f, 0xc1, 0xd3, 0x1f, 0x32, 0x4b, 0x35, 0xdd, 0x1e, 0x8f, 0xb3, 0xfb, 0x7e, 0x43,
	0x3f, 0xf6, 0x1e, 0x70, 0x15, 0x8c, 0xf0, 0x02, 0x16, 0x97, 0x82, 0x73, 0xa6, 0xdb, 0x44, 0x5f,
	0xdc, 0xa7, 0x63, 0x46, 0x0f, 0x6b, 0x5c, 0xbc, 0xf9, 0xf9, 0x3a, 0x67, 0xfa, 0x50, 0xef, 0xa2,
	0xbd, 0xe0, 0x71, 0x2f, 0x10, 0x57, 0x72, 0xdf, 0x5f, 0x8d, 0xdd, 0xcc, 0xac, 0xbd, 0xff, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x53, 0x5e, 0xf5, 0x92, 0x36, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformClient interface {
	GetMyGuilds(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*shared.GuildList, error)
	GetGuild(ctx context.Context, in *shared.IDQuery, opts ...grpc.CallOption) (*shared.Guild, error)
	UpdateGuildData(ctx context.Context, in *GuildData, opts ...grpc.CallOption) (*empty.Empty, error)
	CommitRoles(ctx context.Context, in *Roles, opts ...grpc.CallOption) (*empty.Empty, error)
}

type platformClient struct {
	cc *grpc.ClientConn
}

func NewPlatformClient(cc *grpc.ClientConn) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) GetMyGuilds(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*shared.GuildList, error) {
	out := new(shared.GuildList)
	err := c.cc.Invoke(ctx, "/roleypoly.platform.Platform/GetMyGuilds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetGuild(ctx context.Context, in *shared.IDQuery, opts ...grpc.CallOption) (*shared.Guild, error) {
	out := new(shared.Guild)
	err := c.cc.Invoke(ctx, "/roleypoly.platform.Platform/GetGuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) UpdateGuildData(ctx context.Context, in *GuildData, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/roleypoly.platform.Platform/UpdateGuildData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) CommitRoles(ctx context.Context, in *Roles, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/roleypoly.platform.Platform/CommitRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
type PlatformServer interface {
	GetMyGuilds(context.Context, *empty.Empty) (*shared.GuildList, error)
	GetGuild(context.Context, *shared.IDQuery) (*shared.Guild, error)
	UpdateGuildData(context.Context, *GuildData) (*empty.Empty, error)
	CommitRoles(context.Context, *Roles) (*empty.Empty, error)
}

// UnimplementedPlatformServer can be embedded to have forward compatible implementations.
type UnimplementedPlatformServer struct {
}

func (*UnimplementedPlatformServer) GetMyGuilds(ctx context.Context, req *empty.Empty) (*shared.GuildList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyGuilds not implemented")
}
func (*UnimplementedPlatformServer) GetGuild(ctx context.Context, req *shared.IDQuery) (*shared.Guild, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuild not implemented")
}
func (*UnimplementedPlatformServer) UpdateGuildData(ctx context.Context, req *GuildData) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGuildData not implemented")
}
func (*UnimplementedPlatformServer) CommitRoles(ctx context.Context, req *Roles) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitRoles not implemented")
}

func RegisterPlatformServer(s *grpc.Server, srv PlatformServer) {
	s.RegisterService(&_Platform_serviceDesc, srv)
}

func _Platform_GetMyGuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetMyGuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/roleypoly.platform.Platform/GetMyGuilds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetMyGuilds(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shared.IDQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/roleypoly.platform.Platform/GetGuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetGuild(ctx, req.(*shared.IDQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_UpdateGuildData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuildData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).UpdateGuildData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/roleypoly.platform.Platform/UpdateGuildData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).UpdateGuildData(ctx, req.(*GuildData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_CommitRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Roles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).CommitRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/roleypoly.platform.Platform/CommitRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).CommitRoles(ctx, req.(*Roles))
	}
	return interceptor(ctx, in, info, handler)
}

var _Platform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "roleypoly.platform.Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyGuilds",
			Handler:    _Platform_GetMyGuilds_Handler,
		},
		{
			MethodName: "GetGuild",
			Handler:    _Platform_GetGuild_Handler,
		},
		{
			MethodName: "UpdateGuildData",
			Handler:    _Platform_UpdateGuildData_Handler,
		},
		{
			MethodName: "CommitRoles",
			Handler:    _Platform_CommitRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/platform.proto",
}
