// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth-client.proto

package com_roleypoly_auth_client

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("auth-client.proto", fileDescriptor_de1f50b80a732fe2) }

var fileDescriptor_de1f50b80a732fe2 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0x2d, 0xc9,
	0xd0, 0x4d, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4c,
	0xce, 0xcf, 0xd5, 0x2b, 0xca, 0xcf, 0x49, 0xad, 0x2c, 0xc8, 0xcf, 0xa9, 0xd4, 0x03, 0x29, 0xd0,
	0x83, 0x28, 0x30, 0xe2, 0xe1, 0xe2, 0x72, 0x2c, 0x2d, 0xc9, 0x70, 0x06, 0xf3, 0x92, 0xd8, 0xc0,
	0xea, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xba, 0x94, 0xdd, 0xd5, 0x44, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClientClient is the client API for AuthClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClientClient interface {
}

type authClientClient struct {
	cc *grpc.ClientConn
}

func NewAuthClientClient(cc *grpc.ClientConn) AuthClientClient {
	return &authClientClient{cc}
}

// AuthClientServer is the server API for AuthClient service.
type AuthClientServer interface {
}

// UnimplementedAuthClientServer can be embedded to have forward compatible implementations.
type UnimplementedAuthClientServer struct {
}

func RegisterAuthClientServer(s *grpc.Server, srv AuthClientServer) {
	s.RegisterService(&_AuthClient_serviceDesc, srv)
}

var _AuthClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.roleypoly.auth.client.AuthClient",
	HandlerType: (*AuthClientServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "auth-client.proto",
}
