version: 1

update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: daily
    automerged_updates:
      - match: all
        update_type: semver:minor

  - package_manager: docker
    directory: /
    update_schedule: daily
    automerged_updates:
      - match: all
        update_type: semver:minor

  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match: all
        update_type: semver:minor
