// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared/internal.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	discord "github.com/roleypoly/rpc/discord"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleypolySession_SessionSource int32

const (
	RoleypolySession_OAUTH RoleypolySession_SessionSource = 0
	RoleypolySession_DM    RoleypolySession_SessionSource = 1
)

var RoleypolySession_SessionSource_name = map[int32]string{
	0: "OAUTH",
	1: "DM",
}

var RoleypolySession_SessionSource_value = map[string]int32{
	"OAUTH": 0,
	"DM":    1,
}

func (x RoleypolySession_SessionSource) String() string {
	return proto.EnumName(RoleypolySession_SessionSource_name, int32(x))
}

func (RoleypolySession_SessionSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c67730e27cff8995, []int{1, 0}
}

type RoleypolyUser struct {
	DiscordUser          *discord.User `protobuf:"bytes,1,opt,name=discordUser,proto3" json:"discordUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoleypolyUser) Reset()         { *m = RoleypolyUser{} }
func (m *RoleypolyUser) String() string { return proto.CompactTextString(m) }
func (*RoleypolyUser) ProtoMessage()    {}
func (*RoleypolyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67730e27cff8995, []int{0}
}

func (m *RoleypolyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleypolyUser.Unmarshal(m, b)
}
func (m *RoleypolyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleypolyUser.Marshal(b, m, deterministic)
}
func (m *RoleypolyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleypolyUser.Merge(m, src)
}
func (m *RoleypolyUser) XXX_Size() int {
	return xxx_messageInfo_RoleypolyUser.Size(m)
}
func (m *RoleypolyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleypolyUser.DiscardUnknown(m)
}

var xxx_messageInfo_RoleypolyUser proto.InternalMessageInfo

func (m *RoleypolyUser) GetDiscordUser() *discord.User {
	if m != nil {
		return m.DiscordUser
	}
	return nil
}

type RoleypolySession struct {
	Id                   string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *RoleypolyUser                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Source               RoleypolySession_SessionSource `protobuf:"varint,3,opt,name=source,proto3,enum=roleypoly.RoleypolySession_SessionSource" json:"source,omitempty"`
	CreatedAt            int64                          `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresIn            int64                          `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Extra                map[string]string              `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RoleypolySession) Reset()         { *m = RoleypolySession{} }
func (m *RoleypolySession) String() string { return proto.CompactTextString(m) }
func (*RoleypolySession) ProtoMessage()    {}
func (*RoleypolySession) Descriptor() ([]byte, []int) {
	return fileDescriptor_c67730e27cff8995, []int{1}
}

func (m *RoleypolySession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleypolySession.Unmarshal(m, b)
}
func (m *RoleypolySession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleypolySession.Marshal(b, m, deterministic)
}
func (m *RoleypolySession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleypolySession.Merge(m, src)
}
func (m *RoleypolySession) XXX_Size() int {
	return xxx_messageInfo_RoleypolySession.Size(m)
}
func (m *RoleypolySession) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleypolySession.DiscardUnknown(m)
}

var xxx_messageInfo_RoleypolySession proto.InternalMessageInfo

func (m *RoleypolySession) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoleypolySession) GetUser() *RoleypolyUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RoleypolySession) GetSource() RoleypolySession_SessionSource {
	if m != nil {
		return m.Source
	}
	return RoleypolySession_OAUTH
}

func (m *RoleypolySession) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RoleypolySession) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *RoleypolySession) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterEnum("roleypoly.RoleypolySession_SessionSource", RoleypolySession_SessionSource_name, RoleypolySession_SessionSource_value)
	proto.RegisterType((*RoleypolyUser)(nil), "roleypoly.RoleypolyUser")
	proto.RegisterType((*RoleypolySession)(nil), "roleypoly.RoleypolySession")
	proto.RegisterMapType((map[string]string)(nil), "roleypoly.RoleypolySession.ExtraEntry")
}

func init() { proto.RegisterFile("shared/internal.proto", fileDescriptor_c67730e27cff8995) }

var fileDescriptor_c67730e27cff8995 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0x24, 0x4d, 0x20, 0x53, 0x5a, 0xc2, 0xf2, 0x15, 0x43, 0x41, 0x8c, 0x39, 0x48,
	0x04, 0x49, 0xa0, 0x5e, 0xaa, 0x78, 0xa9, 0x58, 0x50, 0x41, 0x84, 0xad, 0xbd, 0x78, 0x29, 0x69,
	0xb2, 0xd8, 0xc5, 0x98, 0x0d, 0xbb, 0x1b, 0x69, 0x7e, 0xb4, 0xff, 0x41, 0x92, 0x6c, 0x63, 0x0b,
	0xe2, 0x69, 0x32, 0x33, 0xcf, 0xfb, 0xce, 0x64, 0x12, 0x18, 0x89, 0x4d, 0xcc, 0x49, 0x1a, 0xd1,
	0x5c, 0x12, 0x9e, 0xc7, 0x59, 0x58, 0x70, 0x26, 0x19, 0xb2, 0x39, 0xcb, 0x48, 0x55, 0xb0, 0xac,
	0x1a, 0x8f, 0x52, 0x2a, 0x12, 0xc6, 0xd3, 0x48, 0xc5, 0x96, 0xf0, 0x1f, 0x61, 0x80, 0x77, 0xcc,
	0x52, 0x10, 0x8e, 0xae, 0xa0, 0xaf, 0x88, 0x3a, 0x75, 0x35, 0x4f, 0x0b, 0xfa, 0x93, 0xa3, 0xb0,
	0x33, 0x0a, 0x77, 0xfa, 0xba, 0x8d, 0xf7, 0x59, 0xff, 0x4b, 0x07, 0xa7, 0x33, 0x5b, 0x10, 0x21,
	0x28, 0xcb, 0xd1, 0x10, 0x74, 0x9a, 0x36, 0x36, 0x36, 0xd6, 0x69, 0x8a, 0x2e, 0xa0, 0x57, 0xd6,
	0xc6, 0x7a, 0x63, 0xec, 0xee, 0x19, 0x1f, 0xec, 0x81, 0x1b, 0x0a, 0xcd, 0xc0, 0x12, 0xac, 0xe4,
	0x09, 0x71, 0x0d, 0x4f, 0x0b, 0x86, 0x93, 0xf3, 0xdf, 0x78, 0x35, 0x2a, 0x54, 0x71, 0xd1, 0x08,
	0xb0, 0x12, 0xa2, 0x63, 0x80, 0x84, 0x93, 0x58, 0x92, 0x74, 0x15, 0x4b, 0xb7, 0xe7, 0x69, 0x81,
	0x81, 0x6d, 0x55, 0x99, 0xc9, 0xba, 0x4d, 0xb6, 0x05, 0xe5, 0x44, 0xac, 0x68, 0xee, 0x9a, 0x6d,
	0x5b, 0x55, 0x1e, 0x72, 0x74, 0x03, 0x26, 0xd9, 0x4a, 0x1e, 0xbb, 0x96, 0x67, 0x04, 0xfd, 0xc9,
	0xd9, 0x5f, 0xf3, 0xe7, 0x35, 0x38, 0xcf, 0x25, 0xaf, 0x70, 0x2b, 0x1a, 0x4f, 0x01, 0x7e, 0x8a,
	0xc8, 0x01, 0xe3, 0x9d, 0x54, 0xea, 0x16, 0xf5, 0x23, 0xfa, 0x0f, 0xe6, 0x67, 0x9c, 0x95, 0xa4,
	0xb9, 0x86, 0x8d, 0xdb, 0xe4, 0x5a, 0x9f, 0x6a, 0xbe, 0x0f, 0x83, 0x83, 0xd7, 0x41, 0x36, 0x98,
	0xcf, 0xb3, 0xe5, 0xcb, 0xbd, 0xf3, 0x0f, 0x59, 0xa0, 0xdf, 0x3d, 0x39, 0xda, 0xed, 0xe9, 0xeb,
	0xc9, 0x1b, 0x95, 0x9b, 0x72, 0x1d, 0x26, 0xec, 0x23, 0xea, 0x16, 0x8b, 0x78, 0x91, 0x44, 0xed,
	0xff, 0xb0, 0xb6, 0x9a, 0xaf, 0x7c, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x09, 0x58, 0xd3, 0x65,
	0x20, 0x02, 0x00, 0x00,
}
