// source: shared/internal.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var discord_discord_pb = require('../discord/discord_pb.js');
goog.object.extend(proto, discord_discord_pb);
goog.exportSymbol('proto.roleypoly.RoleypolySession', null, global);
goog.exportSymbol('proto.roleypoly.RoleypolySession.SessionSource', null, global);
goog.exportSymbol('proto.roleypoly.RoleypolyUser', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.RoleypolyUser = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.roleypoly.RoleypolyUser, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.RoleypolyUser.displayName = 'proto.roleypoly.RoleypolyUser';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.roleypoly.RoleypolySession = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.roleypoly.RoleypolySession, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.roleypoly.RoleypolySession.displayName = 'proto.roleypoly.RoleypolySession';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.RoleypolyUser.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.RoleypolyUser.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.RoleypolyUser} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.RoleypolyUser.toObject = function(includeInstance, msg) {
  var f, obj = {
    discorduser: (f = msg.getDiscorduser()) && discord_discord_pb.User.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.RoleypolyUser}
 */
proto.roleypoly.RoleypolyUser.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.RoleypolyUser;
  return proto.roleypoly.RoleypolyUser.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.RoleypolyUser} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.RoleypolyUser}
 */
proto.roleypoly.RoleypolyUser.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new discord_discord_pb.User;
      reader.readMessage(value,discord_discord_pb.User.deserializeBinaryFromReader);
      msg.setDiscorduser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.RoleypolyUser.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.RoleypolyUser.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.RoleypolyUser} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.RoleypolyUser.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDiscorduser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      discord_discord_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * optional discord.User discordUser = 1;
 * @return {?proto.roleypoly.discord.User}
 */
proto.roleypoly.RoleypolyUser.prototype.getDiscorduser = function() {
  return /** @type{?proto.roleypoly.discord.User} */ (
    jspb.Message.getWrapperField(this, discord_discord_pb.User, 1));
};


/** @param {?proto.roleypoly.discord.User|undefined} value */
proto.roleypoly.RoleypolyUser.prototype.setDiscorduser = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.RoleypolyUser.prototype.clearDiscorduser = function() {
  this.setDiscorduser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.RoleypolyUser.prototype.hasDiscorduser = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.roleypoly.RoleypolySession.prototype.toObject = function(opt_includeInstance) {
  return proto.roleypoly.RoleypolySession.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.roleypoly.RoleypolySession} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.RoleypolySession.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    user: (f = msg.getUser()) && proto.roleypoly.RoleypolyUser.toObject(includeInstance, f),
    source: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    expiresIn: jspb.Message.getFieldWithDefault(msg, 5, 0),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.roleypoly.RoleypolySession}
 */
proto.roleypoly.RoleypolySession.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.roleypoly.RoleypolySession;
  return proto.roleypoly.RoleypolySession.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.roleypoly.RoleypolySession} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.roleypoly.RoleypolySession}
 */
proto.roleypoly.RoleypolySession.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.roleypoly.RoleypolyUser;
      reader.readMessage(value,proto.roleypoly.RoleypolyUser.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 3:
      var value = /** @type {!proto.roleypoly.RoleypolySession.SessionSource} */ (reader.readEnum());
      msg.setSource(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedAt(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiresIn(value);
      break;
    case 6:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.roleypoly.RoleypolySession.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.roleypoly.RoleypolySession.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.roleypoly.RoleypolySession} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.roleypoly.RoleypolySession.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.roleypoly.RoleypolyUser.serializeBinaryToWriter
    );
  }
  f = message.getSource();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * @enum {number}
 */
proto.roleypoly.RoleypolySession.SessionSource = {
  OAUTH: 0,
  DM: 1
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.roleypoly.RoleypolySession.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.roleypoly.RoleypolySession.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional RoleypolyUser user = 2;
 * @return {?proto.roleypoly.RoleypolyUser}
 */
proto.roleypoly.RoleypolySession.prototype.getUser = function() {
  return /** @type{?proto.roleypoly.RoleypolyUser} */ (
    jspb.Message.getWrapperField(this, proto.roleypoly.RoleypolyUser, 2));
};


/** @param {?proto.roleypoly.RoleypolyUser|undefined} value */
proto.roleypoly.RoleypolySession.prototype.setUser = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.roleypoly.RoleypolySession.prototype.clearUser = function() {
  this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.roleypoly.RoleypolySession.prototype.hasUser = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SessionSource source = 3;
 * @return {!proto.roleypoly.RoleypolySession.SessionSource}
 */
proto.roleypoly.RoleypolySession.prototype.getSource = function() {
  return /** @type {!proto.roleypoly.RoleypolySession.SessionSource} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.roleypoly.RoleypolySession.SessionSource} value */
proto.roleypoly.RoleypolySession.prototype.setSource = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional int64 created_at = 4;
 * @return {number}
 */
proto.roleypoly.RoleypolySession.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.roleypoly.RoleypolySession.prototype.setCreatedAt = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 expires_in = 5;
 * @return {number}
 */
proto.roleypoly.RoleypolySession.prototype.getExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.roleypoly.RoleypolySession.prototype.setExpiresIn = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * map<string, string> extra = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.roleypoly.RoleypolySession.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.roleypoly.RoleypolySession.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};


goog.object.extend(exports, proto.roleypoly);
