name: RPC CI/CD

on: push

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Ensure Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14.x

      - uses: actions/checkout@master

      - uses: actions/cache@master
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Fetch Dependencies & Generate
        run: |
          docker run --rm --mount type=bind,src="$(pwd)",dst=/src --mount type=volume,dst=/src/node_modules roleypoly/rpc-builder

      - name: Smoketest
        run: |
          go vet ./...
          docker run --rm --mount type=bind,src="$(pwd)",dst=/src --mount type=volume,dst=/src/node_modules roleypoly/rpc-builder node hack/smoketest.js

      - name: Check if dirty
        run: test -z "`git status -s`" || (git status && exit 1)

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master

      - name: Ensure Node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Dependencies
        run: |
          npm ci
      
      - name: Release
        run: |
          npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    