name: RPC CI/CD

on: push

jobs:
  validate:
    name: Validate & Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Ensure Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14.x

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Fetch Dependencies & Generate
        run: |
          docker run --rm --mount type=bind,src="$(pwd)",dst=/src --mount type=volume,dst=/src/node_modules roleypoly/rpc-builder

      - name: Smoketest
        run : |
          go vet ./...
          docker run --rm --mount type=bind,src="$(pwd)",dst=/src --mount type=volume,dst=/src/node_modules roleypoly/rpc-builder node hack/smoketest.js

      - name: Check if dirty
        run: test -z "`git status -s`" || (git status && exit 1)

      - name: Release
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run --rm \
            -e GH_TOKEN=${{ secrets.GH_AUTH_TOKEN }} \
            -e NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            -v`pwd`:/src \
              docker.pkg.github.com/roleypoly/devops/semantic-release:latest
